AWSTemplateFormatVersion: 2010-09-09
Description: Gohanya-san App infrastructure (Root Stack)

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Project Name Prefix"
        Parameters:
          - PJPrefix
      - Label:
          default: "Network Configuration"
        Parameters:
          - VPCCIDR
          - PublicSubnetACIDR
          - PublicSubnetCCIDR
          - PrivateSubnetACIDR
          - PrivateSubnetCCIDR
    ParameterLabels:
      VPCCIDR:
        default: "VPC CIDR"
      PublicSubnetACIDR:
        default: "PublicSubnetA CIDR"
      PublicSubnetCCIDR:
        default: "PublicSubnetC CIDR"
      PrivateSubnetACIDR:
        default: "PrivateSubnetA CIDR"
      PrivateSubnetCCIDR:
        default: "PrivateSubnetC CIDR"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  PJPrefix:
    Type: String
    Default: "sagashite-meal"

  IMAGE_TAG:
    Type: String
    Description: "The image tag to deploy. This is passed from CodeBuild."

  InUse:
    Type: String
    Default: "false"
    Description: "Whether to create ALB and ECS tasks. Set to true when creating resources."
    AllowedValues:
      - "true"
      - "false"

  VPCCIDR:
    Type: String
    Default: "10.0.0.0/16"

  PublicSubnetACIDR:
    Type: String
    Default: "10.0.0.0/20"

  PublicSubnetCCIDR:
    Type: String
    Default: "10.0.16.0/20"

  PrivateSubnetACIDR:
    Type: String
    Default: "10.0.128.0/20"

  PrivateSubnetCCIDR:
    Type: String
    Default: "10.0.144.0/20"

Resources:
  # ------------------------------------------------------------#
  #  VPC Nested Stack
  # ------------------------------------------------------------#
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: child/vpc.yaml
      Parameters:
        PJPrefix: !Ref PJPrefix
        VPCCIDR: !Ref VPCCIDR
        PublicSubnetACIDR: !Ref PublicSubnetACIDR
        PublicSubnetCCIDR: !Ref PublicSubnetCCIDR
        PrivateSubnetACIDR: !Ref PrivateSubnetACIDR
        PrivateSubnetCCIDR: !Ref PrivateSubnetCCIDR

  # ------------------------------------------------------------#
  #  RDS Nested Stack
  # ------------------------------------------------------------#
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: child/rds.yaml
      Parameters:
        PJPrefix: !Ref PJPrefix
        VPCCIDR: !Ref VPCCIDR
        VPCId: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnetA: !GetAtt VPCStack.Outputs.PrivateSubnetA
        PrivateSubnetC: !GetAtt VPCStack.Outputs.PrivateSubnetC

  # ------------------------------------------------------------#
  #  ALB Nested Stack
  # ------------------------------------------------------------#
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: child/alb.yaml
      Parameters:
        PJPrefix: !Ref PJPrefix
        InUse: !Ref InUse
        VPCId: !GetAtt VPCStack.Outputs.VPC
        PublicSubnetA: !GetAtt VPCStack.Outputs.PublicSubnetA
        PublicSubnetC: !GetAtt VPCStack.Outputs.PublicSubnetC

  # ------------------------------------------------------------#
  #  ECS Nested Stack
  # ------------------------------------------------------------#
  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: child/ecs.yaml
      Parameters:
        PJPrefix: !Ref PJPrefix
        IMAGE_TAG: !Ref IMAGE_TAG
        InUse: !Ref InUse
        VPCCIDR: !Ref VPCCIDR
        VPCId: !GetAtt VPCStack.Outputs.VPC
        PublicSubnetA: !GetAtt VPCStack.Outputs.PublicSubnetA
        PublicSubnetC: !GetAtt VPCStack.Outputs.PublicSubnetC
        TargetGroup: !GetAtt ALBStack.Outputs.TargetGroup
