version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: sagashite-meal
    AWS_DEFAULT_REGION: ap-northeast-1
    IN_USE: "true" # This variable is used to determine whether to deploy the application or not. Set to "true" to deploy, "false" to skip deployment.

phases:
  pre_build:
    commands:
      - echo "Fetching image tag from SSM..."
      - IMAGE_TAG=$(aws ssm get-parameter --name "/$IMAGE_REPO_NAME/imageTag" --query "Parameter.Value" --output text)
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      # Package CloudFormation template
      - cd infra/cloudformation
      - echo "Packaging CloudFormation template..."
      - aws cloudformation package --template-file root-stack.yaml --s3-bucket sagashite-meal-cfn-template --output-template-file packaged.yaml

      # Deploy CloudFormation stack
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy --template-file packaged.yaml --stack-name sagashite-meal --capabilities CAPABILITY_NAMED_IAM --parameter-overrides ImageTag=$IMAGE_TAG InUse=$IN_USE
